# Generated by Django 3.2.18 on 2023-03-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagsrecipes',
            old_name='tag',
            new_name='tags',
        ),
    ]
