# Generated by Django 3.2.18 on 2023-03-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_tag_tagsrecipes_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
    ]
